### ISSUE TITLE
Review removed Edraak changes

### ISSUE THREAD

**Issue by OmarEdraak** [Edraak/edx-configuration#4]
I copied from #2 into #3 and cleaned it up a bit. While working on #3, I removed the following blocks as they didn't really make sense. Please check them out @devalih and let me know what do you want to do with them.

### Changes

 - [ ] Check with @devalih as I've removed this:
```
# Nginx
# nginx mime types configuration file
# templates: etc/nginx/mime.types.j2
# nginx templates
#   add_header X-Content-Type-Options nosniff;
#   location ~ ^/.well-known/acme-challenge/(?P<token>.*)$ {
#    default_type "text/plain";
#    root {{ COMMON_DATA_DIR }}/letsencrypt;
#    try_files /cms/$token =404;
#    autoindex    on;
#  }
# Edraak
```

 - [ ] Removed the MathJax configs:
```
#tasks:
#- name: Delete old MATHJAX dir
#  file: path="{{ EDXAPP_ARABIC_MATHJAX_DIR }}" state=absent
#
#- name: create {{ EDXAPP_ARABIC_MATHJAX_DEST }} dir
#  file: >
#    path="{{ EDXAPP_ARABIC_MATHJAX_DEST }}" state=directory
#    owner="{{ edxapp_user }}" group="{{ common_web_group }}"
#
#- name: download ARABIC MATHJAX to statics
#  get_url: >
#    url="{{ EDXAPP_ARABIC_MATHJAX_SRC }}" dest="{{ EDXAPP_ARABIC_MATHJAX_DEST }}/arabic.js"
#    owner="{{ edxapp_user }}" group="{{ common_web_group }}"
```

- [ ] Removed from prod

```

# TIME SAVING on DEV

#COMMON_APP_DIR: /edx/app
#COMMON_CFG_DIR: /edx/etc
#COMMON_DATA_DIR: /edx/var
#common_web_group: www-data
#COMMON_LOG_DIR: /edx/var/log


#nginx_default_sites:
#- marketing

#EDXAPP_GIT_IDENTITY: ../edraak/keys/id_rsa
#EDXAPP_USE_GIT_IDENTITY: True

#EDXAPP_XQUEUE_URL: 'http://internal-edraak-Xqueue-ELB-827148671.us-west-2.elb.amazonaws.com'

#EDXAPP_MYSQL_REPLICA_HOST: "-"
```

- [ ] Removed

```
# TODO: search for this ! EDXAPP_CORS_ORIGIN_WHITELIST
# TODO: CDN_VIDEO_URLS

## insights
#INSIGHTS_NGINX_PORT: "80"
#INSIGHTS_SSL_NGINX_PORT: "443"
```
